### PR TITLE
Fix configuration cache compatibility

### LINKED ISSUE #82: Gradle Configuration Cache support
Running `./gradlew --configuration-cache testDebugComposer` with composer 1.0.0-rc08 on Gradle 7.0.1, AGP 4.1.2, Kotlin 1.4.32 results in error

> What went wrong:
Configuration cache problems found in this build.
> 
> 5 problems were found storing the configuration cache, 4 of which seem unique.
> Task `:database:testDebugComposer` of type `com.trevjonez.composer.ComposerTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
>  See https://docs.gradle.org/7.0.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

There are suggested replacement available at the documentation. Although I haven't check if they are suitable replacements.

### PR DESCRIPTION
**Pull request by plastiv**
Fixes #82 

Test is taken from https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:testing

Gradle 7 update is not required as replacement apis are available in previous gradle version. I've bumped them together since I wanted to additionally to CI verify fork with working project which is already on gradle 7. Before plugin is published on mavencentral it is possible to check with local  dependency substitution.  

```
// settings.gradle
includeBuild("/Users/plastiv/Projects/composer-gradle-plugin") {
    dependencySubstitution {
        substitute(module("com.trevjonez.composer:plugin")).with(project(":plugin"))
    }
}
```

### CODE REVIEW

File: plugin/src/main/kotlin/com/trevjonez/composer/ComposerTask.kt [hunk 1]
```diff
@@ -88,9 +85,9 @@ abstract class ComposerTask : JavaExec(), ComposerConfigurator, ComposerTaskDsl
     val buildDirectory = project.layout.buildDirectory
     outputDir.convention(buildDirectory.dir(ComposerConfig.DEFAULT_OUTPUT_DIR))
     workDir.convention(buildDirectory.dir(ComposerConfig.DEFAULT_WORK_DIR))
-    setWorkingDir(workDir.map { it.also { it.asFile.mkdirs() } })
```
Comment (plastiv) [inline plugin/src/main/kotlin/com/trevjonez/composer/ComposerTask.kt:91]: This line errors on Gradle 7. Quote from user guide

> **Querying the mapped value of a provider before the producer has completed is now an error**
>
> Gradle 6.x warns users about the wrong behavior and then returns a possibly incorrect provider
value. Starting with 7.0 the same case will produce an error. Plugins and build scripts should be
adjusted to query the mapped value of a provider, for example a task output property, after the task
has completed.

Resolving output property before task finishes is now an error. I'm not 100% sure, but it looks like gradle will mkdir folder/file properties automatically.

**Comment by dkostyrev** [comment]
@trevjonez any plans on reviewing and merging this?

**Comment by trevjonez** [comment]
@dkostyrev sorry about that delay have not been paying close enough attention to this project lately.

I just cloned and will do some other touchups to make sure things are in decent shape and publish a new build out.
