### PR TITLE
Pass verboseOutput argument to adb install command

### LINKED ISSUE #59: `verboseOutput` `keepOutput` args are not passed to commander
It looks like verbose and output flags are not passed to the commander process.

1) Process logs are guarded:

https://github.com/trevjonez/composer-gradle-plugin/blob/271a5a5ebceb1ea779c800cbcdd1e1a82648f337/commander/os/src/main/kotlin/com/gojuno/commander/os/Processes.kt#L105-L107

2) Logs are turned off by default:

https://github.com/trevjonez/composer-gradle-plugin/blob/271a5a5ebceb1ea779c800cbcdd1e1a82648f337/commander/os/src/main/kotlin/com/gojuno/commander/os/Processes.kt#L29-L32

3) process is unconditionally being called AFAIS:

https://github.com/trevjonez/composer-gradle-plugin/blob/271a5a5ebceb1ea779c800cbcdd1e1a82648f337/commander/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt#L94-L98

### My use case. 

I am running composer. APK install is failing on the CI and I don't see adb message to get a sense why is it failing. Turning `verboseOutput=true` `keepOutput=true` flags in plugin doesn't help, since apparently flags are not being passed down. So at the end all I see is next:

```
> Task :storage:testDebugComposer
[Tue Feb 25 19:35:37 CET 2020]: Args(appApkPath=/Users/user/Projects/project/storage/build/outputs/apk/androidTest/debug/storage-debug-androidTest.apk, testApkPath=/Users/user/Projects/project/storage/build/outputs/apk/androidTest/debug/storage-debug-androidTest.apk, testRunner=, shard=true, outputDirectory=/Users/user/Projects/project/storage/build/reports/composer/debug, instrumentationArguments=[disableAnalytics, true], verboseOutput=true, keepOutputOnExit=true, devices=[], devicePattern=, installTimeoutSeconds=120, failIfNoTests=true, runWithOrchestrator=false, extraApks=[])
[Tue Feb 25 19:35:37 CET 2020]: 1 connected adb device(s): [AdbDevice(id=emulator-5554, model=Android SDK built for x86_64, online=true)]
[Tue Feb 25 19:35:37 CET 2020]: [emulator-5554] 1 APK to install
[Tue Feb 25 19:35:37 CET 2020]: [emulator-5554] Acquiring lock
[Tue Feb 25 19:35:37 CET 2020]: [emulator-5554] Lock acquired
[Tue Feb 25 19:35:37 CET 2020]: [emulator-5554] Installing apk... pathToApk = /Users/user/Projects/project/storage/build/outputs/apk/androidTest/debug/storage-debug-androidTest.apk
[Tue Feb 25 19:35:47 CET 2020]: [emulator-5554] Failed to install apk /Users/user/Projects/project/storage/build/outputs/apk/androidTest/debug/storage-debug-androidTest.apk
Task :storage:testDebugComposer in storage Finished

> Task :storage:testDebugComposer FAILED
:storage:testDebugComposer (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 10.469 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':storage:testDebugComposer'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

Which isn't very helpful since it doesn't contain any error message.

### PR DESCRIPTION
**Pull request by plastiv**
Enabling log output for #59

### CODE REVIEW

File: commander/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt [hunk 1]
```diff
@@ -90,11 +90,12 @@ fun connectedAdbDevices(): Single<Set<AdbDevice>> = process(listOf(adb, "devices
 
 fun AdbDevice.log(message: String) = com.gojuno.commander.os.log("[$id] $message")
 
-fun AdbDevice.installApk(pathToApk: String, timeout: Pair<Int, TimeUnit> = 2 to MINUTES): Observable<Unit> {
+fun AdbDevice.installApk(pathToApk: String, timeout: Pair<Int, TimeUnit> = 2 to MINUTES, logErrors: Boolean = false): Observable<Unit> {
```
Comment (plastiv) [inline commander/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt:93]: I see 3 variable names for this boolean - `verboseOutput`, `logErrors`, `print`. I have used `logErrors` for consistency with methods below:

https://github.com/trevjonez/composer-gradle-plugin/blob/5cf9ffafa02185cb82e30d3022d934774955925b/commander/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt#L163

https://github.com/trevjonez/composer-gradle-plugin/blob/5cf9ffafa02185cb82e30d3022d934774955925b/commander/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt#L178

Comment (trevjonez) [reply commander/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt:93]: Could probably use a closer pass to unify the naming. seems like it is more often just a `print` boolean. I'm not worried about it, minutia.

**Comment by trevjonez** [comment]
I think this is probably good to go, but I want to add a test case to cover it. There will be extra work in setup and tear down though. I am thinking build an apk with matching package name with a higher version code. then run the normal flow so we can see it implode and verify the result is to our liking.

I should have some time tonight to get it done.
